Repository 2022-4J-group-O/Main, pull requests merged in 2023-01, with the labels that each got.

#71 wdissolveを追加
  game/scripts/f1/r1/events/door_clicked.rpy
  game/scripts/f1/r1/events/opening.rpy
  game/scripts/f1/r2/events/angry.rpy
  game/scripts/f1/r2/events/chest_clicked.rpy
  game/scripts/f1/r2/events/clicked_hidden.rpy
  game/scripts/f1/r2/events/door_clickked.rpy
  game/scripts/f1/r2/events/robot_clicked.rpy
  game/scripts/f1/r2/events/vase_clicked.rpy
  game/scripts/f1/r3/events/opening.rpy
  game/scripts/f2/r1/events/opening.rpy
  game/scripts/f3/r1/events/opening.rpy
  game/scripts/menu/events/l1_clicked.rpy
  game/scripts/menu/events/l2_clicked.rpy
  game/scripts/menu/events/l3_clicked.rpy
  game/scripts/menu/events/opening.rpy
  game/scripts/title/events/opening.rpy
  game/scripts/title/events/start_clicked.rpy
  game/zz_late_eval/labels/labels01.rpy
Labels: effect

#74 部屋の生成の実装とバグの解消その他
  default_game_data/loadfile1/room3/Box
  default_game_data/loadfile1/room3/DoorA
  default_game_data/loadfile1/room3/Fridge 1
  default_game_data/loadfile1/room3/Fridge 2
  default_game_data/loadfile1/room3/Fridge 3
  default_game_data/loadfile1/room3/Fridge 4
  default_game_data/loadfile1/room3/Fridge.zip
  default_game_data/loadfile1/room3/text.txt
  default_game_data/loadfile1/room3/文字化けテキスト.txt
  default_game_data/loadfile2/room2/picture frame1/black.png
  default_game_data/loadfile2/room2/picture frame1/ijli.png
  default_game_data/loadfile2/room2/picture frame2/srps.png
  default_game_data/loadfile2/room2/picture frame2/white.png
  default_game_data/loadfile2/room2/picture frame3/black+white.png
  default_game_data/loadfile2/room2/vault/mbfh.png
  default_game_data/loadfile2/room2/vault/rnjk.png
  default_game_data/loadfile2/room2/vault/top_secret1.png
  default_game_data/loadfile2/room2/vault/top_secret2.png
  default_game_data/title/Start
  game/scripts/event_global/obj_clicked.rpy
  game/scripts/f1/r1/start.rpy
  game/scripts/f1/r2/events.rpy
  game/scripts/f1/r2/start.rpy
  game/scripts/f1/r3/start.rpy
  game/scripts/title/start.rpy
  game/zz_late_eval/functions/function01.rpy
  game/zz_late_eval/functions/function02.rpy
  ファイル退避用/Start
  ファイル退避用/archive.tar.gz
  ファイル退避用/document.docx
  ファイル退避用/document.zip
  ファイル退避用/door_to_1-4.png
  ファイル退避用/fridge.7z
  ファイル退避用/fridge_pass.7z
  ファイル退避用/fridge_pass.zip
Labels: system

#77 クリック可能displayableにフォーカスしてると会話が読み進められないバグを修正
  game/scripts/event_global/obj_clicked.rpy
  game/scripts/event_global/obj_screen.rpy
  game/scripts/menu/events/l1_clicked.rpy
  game/scripts/menu/events/l2_clicked.rpy
  game/scripts/menu/events/l3_clicked.rpy
  game/scripts/menu/events/opening.rpy
Labels: system

#93 ロボット君がコピー先に同名のファイルがあると壊れる問題を修正
  game/scripts/f1/r2/events.rpy
Labels: bug

#89 ディレクトリ生成と画面更新のタイミングを調整
  game/scripts/f1/r1/start.rpy
  game/scripts/f1/r2/start.rpy
  game/scripts/f1/r3/start.rpy
  game/scripts/title/start.rpy
Labels: bug, effect

#86 object関連の不具合を解消
  game/data/hash_list/Box.png
  game/images/f1r3/box png.png
  game/scripts/event_global/obj_clicked.rpy
  game/scripts/event_global/obj_screen.rpy
  game/zz_late_eval/functions/function01.rpy
Labels: system, effect
